inherit_from: .rubocop_todo.yml

Style/Documentation:
  Exclude:
    - app/helpers/application_helper.rb
    - app/helpers/articles_helper.rb
    - app/mailers/application_mailer.rb
    - app/models/application_record.rb
    - config/application.rb
    - db/migrate/**.*
